version: '3.8'
services:
  bot:
    build: .
    command: python bot/main.py
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: eldoria
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6
volumes:
  pgdata: 